[package]
name = "extension-pack"
description = "Format for distributing extensions to applications."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]